name: codebarr
services:
  codebarr:
    # image: codebarr:local
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      tags: 
        - "codebarr:local"
    container_name: codebarr
    ports:
      - 5083:5083
    environment:
      - SECRET_KEY=your_secret_key_here     # Flask secret key (randomly-generated, long string)
      - CODEBARR_USERNAME=user              # Change as needed
      - CODEBARR_PASSWORD=password          # Change as needed
      - LIDARR_URL=https://localhost:8686   # Lidarr URL
      - LIDARR_API_KEY=yourkey              # Lidarr API key
      - LIDARR_ROOT_FOLDER_PATH=/music      # Music root folder
      - LIDARR_QUALITY_PROFILE=2            # Quality profile ID
      - LIDARR_METADATA_PROFILE=9           # Metadata profile ID
      - LIDARR_ARTIST_MONITORED=false       # Monitor artist/album by default
      - LIDARR_MONITOR_NEW_ITEMS=none       # How new releases are handled (options: all, none, new)
      - LIDARR_SEARCH_ON_ADD=false          # Auto-search missing albums
    restart: unless-stopped